---
title: "MTH208: Worksheet 16"
format: 
  pdf:
    documentclass: article
editor: visual
geometry: margin=1in
header-includes:
   - \usepackage{amsmath, amssymb, setspace}
   - \onehalfspacing
   - \usepackage{etoolbox} 
   - \makeatletter 
   - \preto{\@verbatim}{\topsep=3pt \partopsep=3pt } 
   - \makeatother
---

## Using Quarto and RMarkdown

All of your worksheet documents have been written in Quarto --- Quarto is an improved version of RMarkdown.

RMarkdown is a R-integrated language interface that allows the development of reproducible documents and website. Quarto is a modified visual editor that allows you to integrate all sorts of code into the document.

A clear purpose of RMarkdown is the following: If there is code involved to generate any plot/tables etc in document, then to ensure that all work is reproducible, document should be able to contain the code used to make the document.

Additionally, RMarkdown is TeX enabled, we are able to write equations simply and beautifully.

[Your job in this assignment will be to recreate the document `sample.pdf`.]{.underline} You may create an \`html\` page instead of a pdf.

Here are some resources you will need:

-   Markdown basics: <https://quarto.org/docs/authoring/markdown-basics.html>

-   Chunk options in Quarto <https://quarto.org/docs/computations/execution-options.html>

-   List of mathematical commands: <https://oeis.org/wiki/List_of_LaTeX_mathematical_symbols>

-   List of mathematical symbols: <https://www.cmor-faculty.rice.edu/~heinken/latex/symbols.pdf>
